name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
      
jobs:
  build:
    runs-on: macos-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up R
        uses: r-lib/actions/setup-r@v2 
        with:
          r-version: '4.4.1'  

      - name: Install dependencies
        run: |
          install.packages('devtools') 
          devtools::install_deps(dep = TRUE)  

      - name: Check package
        run: |
          library(devtools)
          devtools::check()  
